// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfz-vkh7RQ_xhEC7OyOioVzF_TdULn9Bc',
    appId: '1:598692532665:web:eafc73eba32ec66a49e668',
    messagingSenderId: '598692532665',
    projectId: 'tourismapp-9595d',
    authDomain: 'tourismapp-9595d.firebaseapp.com',
    storageBucket: 'tourismapp-9595d.firebasestorage.app',
    measurementId: 'G-L0XKYMS5T7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5Y52E9-EGQTMo9vwLb-keEyl67VGUE4A',
    appId: '1:598692532665:android:8bd8d6df8ec5a30349e668',
    messagingSenderId: '598692532665',
    projectId: 'tourismapp-9595d',
    storageBucket: 'tourismapp-9595d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM8xMgnMZBvCDHRTtcqYijldWN8BfQLIg',
    appId: '1:598692532665:ios:2260de042c9d476e49e668',
    messagingSenderId: '598692532665',
    projectId: 'tourismapp-9595d',
    storageBucket: 'tourismapp-9595d.firebasestorage.app',
    iosBundleId: 'com.example.communityTouringRwanda',
  );
}
